# -*- coding: utf-8 -*-
"""AI/MLOps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16PCl3MR_f0gIfBnQkQKOvKpGnk0Dxvth
"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Array: ",arr)
print("Mean: ",np.mean(arr))
print("Median: ",np.median(arr))
print("Standard Deviation: ",np.std(arr))

matrix = np.array([[1, 2],[3, 4]])
print("Matrix: \n", matrix)
print("Transpose: \n", matrix.T)

import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'salary': ['50000', '60000', '75000']
}
df = pd.DataFrame(data)

print(df.head())
print(df.describe())
print(df[df["Age"]>=30])

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 4))
plt.bar(df['Name'], df['salary'], color="skyblue")
plt.title('Salary of Enployee')
plt.xlabel('Name')
plt.ylabel('salary')
plt.show()
#

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Create DataFrame
data = pd.DataFrame({
    "Age": [25, 30, 35, 40],
    "city": ["pune", "mumbai", "delhi", "pune"],
    "salary": [50000, 60000, 75000, 90000]
})

print("Original Data")
print(data)

# Fill missing values (if any)
data["Age"] = data["Age"].fillna(data["Age"].mean())
data["city"] = data["city"].fillna(data["city"].mode()[0])

# Encode city names
le = LabelEncoder()
data["City_encoded"] = le.fit_transform(data["city"])

# Scale salary
scaler = StandardScaler()
data["salary_scaled"] = scaler.fit_transform(data[["salary"]])

print("\nProcessed Data")
print(data)

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

data = pd.read_csv("employees.csv")

print("========== ORIGINAL DATA ==========")
print(data)

print("\nMissing Values:")
print(data.isnull().sum())

data["Age"] = data["Age"].fillna(data["Age"].mean())

data["Department"] = \
data["Department"].fillna(data["Department"].mode()[0])

data["Salary"] = \
data["Salary"].fillna(data["Salary"].mean())

encoder = LabelEncoder()

data["Department_Encoded"] = \
encoder.fit_transform(data["Department"])

scaler = StandardScaler()

data["Salary_Scaled"] = scaler.fit_transform(data[["Salary"]])

print("\n=============CLEANED DATA============")
print(data)

print("\nMissing Values After Cleaning")
print(data.isnull().sum())

# Step 1: Import Libraries
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score,confusion_matrix

# Step 2: Load data
iris = load_iris()

X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

print(X.head())

# Step 3: Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Training samples: {len(X_train)}, Testing samples: {len(X_test)}")

# Step 4: Train the model
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Step 5: Make predictions
y_pred = model.predict(X_test)

# Step 6: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average="macro")
recall = recall_score(y_test, y_pred, average="macro")

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Step 1: Import Libraries
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    confusion_matrix,
    classification_report
)

# Step 2: Load Dataset
iris = load_iris()

X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

print("First 5 Rows of Dataset:")
print(X.head())

# Step 3: Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(f"\nTraining Samples: {len(X_train)}")
print(f"Testing Samples: {len(X_test)}")

# Step 4: Train Random Forest Model
model = RandomForestClassifier(
    n_estimators=100,   # Number of trees
    random_state=42
)

model.fit(X_train, y_train)

# Step 5: Predict
y_pred = model.predict(X_test)

# Step 6: Evaluate Model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average="macro")
recall = recall_score(y_test, y_pred, average="macro")
cm = confusion_matrix(y_test, y_pred)

# Step 7: Print Results
print("\n===== Model Performance =====")
print(f"Accuracy : {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall   : {recall:.2f}")

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

# Step 8: Feature Importance
importance = pd.DataFrame({
    "Feature": iris.feature_names,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(by="Importance", ascending=False)

print("\nFeature Importance:")
print(importance)

# Step 1: Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay
)

# Step 2: Load CSV Dataset
data = pd.read_csv("decision_tree_dataset_1000.csv")

print("First 5 Rows:")
print(data.head())

# Step 3: Separate Features and Target
# Assumes the last column is the target
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

print("\nFeature Columns:")
print(X.columns)

print("\nTarget Classes:")
print(y.unique())

# Step 4: Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Step 5: Train Random Forest Model
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

# Step 6: Prediction
y_pred = model.predict(X_test)

# Step 7: Evaluation
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

print("\n===== Model Performance =====")
print(f"Accuracy : {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall   : {recall:.2f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Step 8: Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)

# Step 9: Plot Confusion Matrix
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=model.classes_
)

disp.plot(cmap="Blues")
plt.title("Random Forest Confusion Matrix")
plt.show()

# Step 10: Feature Importance
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print("\nFeature Importance:")
print(importance)

import pickle
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Load dataset
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Save model
with open("iris_model.pkl", "wb") as file:
    pickle.dump(model, file)

print("Model saved as iris_model.pkl")